#! /bin/sh
### BEGIN INIT INFO
# Provides:          phpdlna
# Required-Start:    $local_fs $remote_fs $network $syslog $named
# Required-Stop:     $local_fs $remote_fs $network $syslog $named
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: upnp
# Description:       This file starts the upnp daemon
### END INIT INFO

# Author: Michael Bernstein

# Do NOT "set -e"

# PATH should only include /usr/* if it runs after the mountnfs.sh script
PATH=/sbin:/usr/sbin:/bin:/usr/bin
DESC="announce phpdlna"
NAME=announce
DAEMON=/usr/sbin/$NAME
PIDFILE=/var/run/$NAME.pid
SCRIPTNAME=/etc/init.d/phpdlna

# Load the VERBOSE setting and other rcS variables
. /lib/init/vars.sh

# Define LSB log_* functions.
# Depend on lsb-base (>= 3.2-14) to ensure that this file is present
# and status_of_proc is working.
. /lib/lsb/init-functions

case "$1" in
  start)
	IP_ADDR=`ifconfig eth0 | grep "inet addr" | cut -f 2 -d ":" | cut -f 1 -d " "`
	PR_IP_ADDR=`fgrep presentationURL /var/www/phpdlna/rootDesc.xml | cut -f 3 -d "/"`
	if [ ! -z $IP_ADDR ] ; then
		if [ ! "x$IP_ADDR" = "x$PR_IP_ADDR" ] ; then
			[ "$VERBOSE" != no ] && log_daemon_msg "Change Presentation URL"
			head -n 16 /var/www/phpdlna/rootDesc.xml > /tmp/rootDesc.xml
			echo "<presentationURL>http://$IP_ADDR/</presentationURL>" >> /tmp/rootDesc.xml
			tail -n 4 /var/www/phpdlna/rootDesc.xml >> /tmp/rootDesc.xml
			mv /tmp/rootDesc.xml /var/www/phpdlna/rootDesc.xml
			chmod 6444 /var/www/phpdlna/rootDesc.xml
		fi
		[ "$VERBOSE" != no ] && log_daemon_msg "Starting $DESC" "$NAME"
		start-stop-daemon --background --start --exec $DAEMON -- -i eth0 -l "http://$IP_ADDR:80/phpdlna/rootDesc.xml"
		[ "$VERBOSE" != no ] && log_end_msg 0
	fi
	;;
  stop)
	[ "$VERBOSE" != no ] && log_daemon_msg "Stopping $DESC" "$NAME"
	start-stop-daemon --stop --quiet --retry=TERM/30/KILL/5 --name $NAME
	[ "$VERBOSE" != no ] && log_end_msg 0
	;;
  status)
	status_of_proc "$DAEMON" "$NAME" && exit 0 || exit $?
	;;
  restart|force-reload)
	#
	# If the "reload" option is implemented then remove the
	# 'force-reload' alias
	#
	[ "$VERBOSE" != no ] && log_daemon_msg "Restarting $DESC" "$NAME"
	start-stop-daemon --stop --quiet --retry=TERM/30/KILL/5 --name $NAME
	IP_ADDR=`ifconfig eth0 | grep "inet addr" | cut -f 2 -d ":" | cut -f 1 -d " "`
	PR_IP_ADDR=`fgrep presentationURL /var/www/phpdlna/rootDesc.xml | cut -f 3 -d "/"`
	if [ ! -z $IP_ADDR ] ; then
		if [ ! "x$IP_ADDR" = "x$PR_IP_ADDR" ] ; then
			[ "$VERBOSE" != no ] && log_daemon_msg "Change Presentation URL"
			head -n 16 /var/www/phpdlna/rootDesc.xml > /tmp/rootDesc.xml
			echo "<presentationURL>http://$IP_ADDR/</presentationURL>" >> /tmp/rootDesc.xml
			tail -n 4 /var/www/phpdlna/rootDesc.xml >> /tmp/rootDesc.xml
			mv /tmp/rootDesc.xml /var/www/phpdlna/rootDesc.xml
			chmod 6444 /var/www/phpdlna/rootDesc.xml
		fi
		[ "$VERBOSE" != no ] && log_daemon_msg "Starting $DESC" "$NAME"
		start-stop-daemon --background --start --exec $DAEMON -- -i eth0 -l "http://$IP_ADDR:80/phpdlna/rootDesc.xml"
	fi
	;;
  *)
	echo "Usage: $SCRIPTNAME {start|stop|status|restart|force-reload}" >&2
	exit 3
	;;
esac

:
